name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - name: build
        run: |
          yarn
          yarn build
      - name: Create branches
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release-dist'
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1
        env:
          key: master
          branches: release-dist
          files: README.md